//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_M_H.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appoint_Request
    {
        public int Id { get; set; }
        public int sender_Id { get; set; }
        public int reciever_Id { get; set; }
        public Nullable<System.DateTime> send_date { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> response_Date { get; set; }
        public Nullable<System.DateTime> required_appointment_date { get; set; }
        public string subject { get; set; }
        public string content { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
