//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_M_H.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthTip
    {
        public int Id { get; set; }
        public int doc_Id { get; set; }
        public string tips_Type { get; set; }
        public string ImageURL { get; set; }
        public string tips_Content { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> tips_Date { get; set; }
    }
}
