//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_M_H.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service1
    {
        public int Id { get; set; }
        public string ImageUrl1 { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
        public string ImageUrl2 { get; set; }
        public string ImageUrl3 { get; set; }
        public string iconClass { get; set; }
        public string shortDesc { get; set; }
    }
}
